#!/usr/bin/env python3
"""Reconstruct the named getters from the schema and emit a caller for each.

Every generated accessor is declared in ufconfig_fields_generated.h as

    UfConfigStatus UfConfigGetXxxYyy(const struct UfConfig *h, UfConfigValue *out);

so the names are read back from the artefact rather than recomputed from the
paths: a second implementation of the naming scheme is a second thing to get
wrong, and it would agree with the generator only until one of them changed.

What this produces is a translation unit that *names* every accessor and calls
it.  That is what makes it worth linking: a getter the generator emitted but
which nothing references is still a symbol a consumer may reach for, and this
is the only place that reaches for all of them.  A missing symbol, a signature
that drifted, or an accessor left out of the header is a link or compile error
here rather than a surprise in a consumer.

    make_named_getters.py <fields_generated.h> <named_getters.c> <schema-name>
"""
import re
import sys
from pathlib import Path

DECL = re.compile(r'^UfConfigStatus\s+(UfConfigGet\w+)\s*\(\s*const struct UfConfig\s*\*\s*\w+\s*,\s*UfConfigValue\s*\*\s*\w+\s*\)\s*;', re.M)
# The enum carries the field path as a trailing doc comment:
#   UF_CONFIG_FIELD_REQ_MUST = 0, ///< req.must
ENUM = re.compile(r'^\s*(UF_CONFIG_FIELD_[A-Z0-9_]+)\s*=\s*(\d+)\s*,\s*///<\s*(\S+)', re.M)


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    header, out_path, schema = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    text = header.read_text(encoding="utf-8")

    getters = DECL.findall(text)
    if not getters:
        sys.exit(f"no accessors found in {header} — has the generator changed its emitter?")

    # Paired by position: the enum is emitted in the same order as the accessors,
    # and both come from the same walk of the schema.
    paths = [m.group(3) for m in ENUM.finditer(text)]
    if len(paths) != len(getters):
        sys.exit(f"{len(paths)} enum entries against {len(getters)} accessors — "
                 f"they are emitted from one walk and must be equal")

    lines = [
        "/* DO NOT EDIT — generated by make_named_getters.py from",
        f"   {header.name}, itself generated from {schema}. */",
        "",
        "#include <uflib/ufconfig/ufconfig.h>",
        "",
        "#include <string.h>",
        "",
        "/*!",
        " * One accessor and the field it reads.",
        " */",
        "typedef struct {",
        "  const char *path;   /*!< the field this accessor reads */",
        "  const char *name;   /*!< the accessor itself, for diagnostics */",
        "  UfConfigStatus (*get)(const UfConfig *h, UfConfigValue *out);",
        "} UfConfigNamedGetter;",
        "",
        "/*!",
        " * Calls every named getter the schema produced.",
        " *",
        " * @return how many answered OK.  A getter that could not be called at all",
        " *         is a link error, not a low count — which is the point: this",
        " *         reaches all of them by name.",
        " */",
        "int UfConfigCallAllNamedGetters(UfConfig *h)",
        "{",
        "  UfConfigValue v;",
        "  int           ok = 0;",
        "  memset(&v, 0, sizeof(v));",
        "",
    ]
    for g in getters:
        lines.append(f"  if ({g}(h, &v) == UF_CONFIG_OK) ok++;")
    # An indexed table as well, so a caller can compare the named route against
    # the path route and the index route for the same field.  The three should
    # agree; a test that can only ask "did any of them fail" cannot say which.
    lines += [
        "",
        f"  return ok;  /* of {len(getters)} accessors */",
        "}",
        "",
        "/*!",
        " * The accessors by index, so each can be compared against the same field",
        " * reached by path and by generated id.",
        " */",
        "const UfConfigNamedGetter g_ufconfig_named_getters[] = {",
    ]
    for g, fld in zip(getters, paths):
        lines.append(f'  {{ "{fld}", "{g}", {g} }},')
    lines += [
        "};",
        "",
        f"const int g_ufconfig_named_getter_count = {len(getters)};",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(getters)} accessors and {len(paths)} field paths -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
