find_package(Doxygen)
if (DOXYGEN_FOUND)
    message("doxygen: CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}, CMAKE_CURRENT_BINARY_DIR: ${CMAKE_CURRENT_BINARY_DIR}")
    set(DOXYGEN_IN ${CMAKE_CURRENT_SOURCE_DIR}/doxygen/Doxyfile.in)
    set(DOXYGEN_OUT ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile)

    configure_file(${DOXYGEN_IN} ${DOXYGEN_OUT} @ONLY)
    message("Doxygen build started")

    add_custom_target( ${_PROJECT_NAME}_doxygen
        ALL #make it part of 'make all'
        COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_OUT}
        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
        COMMENT "Generating API documentation with Doxygen"
        VERBATIM )

    # http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.11.jar/download
    find_program(PLANT_UML_PATH plantuml.jar PATH_SUFFIXES PlantUML plantuml Plantuml
            PATHS /opt/bin /usr/share /usr/local/share/ /usr/local/bin c/Program\ Files* )
    if(NOT PLANT_UML_PATH)
        message(WARNING "Looking for PlantUML - not found, some UML diagrams will not be generated via doxygen.")
    else()
        message(STATUS "  + PlantUML - for custom UML             YES ")
    endif()

    #sudo apt install graphviz
    #Search for DOT for autogenerated UML diagrams from doxygen
    find_program(DOT_PATH dot PATH_SUFFIXES graphviz2.38/bin graphviz/bin)
    if(NOT DOT_PATH)
        message(WARNING "Looking for DOT (Graphviz) - not found, some UML diagrams will not be generated via doxygen.")
    else()
        message(STATUS "  + Graphviz/Dot - for generated graphs   YES ")
    endif()

else (DOXYGEN_FOUND)
    message("Doxygen need to be installed to generate the doxygen documentation")
endif(DOXYGEN_FOUND)